### ISSUE TITLE
Discrepancies in Moment-Cuvature results

### ISSUE THREAD

**Issue by DanielGMorenaFhecor** [fib-international/structuralcodes#144]
When calculating the moment-curvature diagram, discrepancies were found compared to established software.  

 
@MestreCarlos prepared examples, illustrations, and notes to track this issue in Point 11 explained [this file](https://github.com/fib-international/structuralcodes/blob/a48150c72c59b20f3fa8d481ee5191e1b3cdf67e/Issues.ipynb)

**Comment by talledodiego** [comment]
I think the issue may be the same as in #140 #141 #142. 
Please take a look if this is the case. Otherwise we can go deeper into it.

Quick responses to Point 11:

> Why only return the negative domain of curvature with theta=0? Wouldn't it be better to have the whole domain instead of use theta parameter for that?

_See response to #142_
> The moment-curvature results should start at (0,0). I miss that point.

_It is just a matter of choice include or not the point (0,0). It is not a problem to add a (0,0) when obtained results. With modification by @mortenengen for better defining the list of curvatures I think this can be done as well._

**Comment by mortenengen** [comment]
`.calculate_moment_curvature()` now accepts the keyword argument `chi_first` which can be set to `0.0` to include this value in the list of curvatures 😃 

I am closing this issue, since it seems to cover the same topic as #140, #141 and #142, but it highlights the need for a careful description of the coordinate system in the docs.
