### ISSUE TITLE
Quickstart example

### ISSUE THREAD

**Issue by kengwit** [fib-international/structuralcodes#172]
I'm trying to run the example from the quickstart: https://fib-international.github.io/structuralcodes/quickstart/index.html#quickstart

1) I am getting this warning:
Python310\lib\site-packages\shapely\set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)

Any issues here?

2) How do I plot the cross section?

Thanks,

**Comment by mortenengen** [comment]
Thanks for posting the issue, @kengwit 😃 

While trying to reproduce your issue, we noticed there was a slight bug in how the quickstart example was broken down into chunks in the docs. This is fixed in #173, and a [new version](https://fib-international.github.io/structuralcodes/quickstart/) is up and running.

To your questions.

1. I was not able to reproduce the warning that you posted. Could you please provide more details about the environment you are running in? Great if you could at least provide the Python version, although I assume it is 3.10-something, and a list of the installed libraries, e.g. the output of `python -m pip list`.

2. One way to visualize your section is to run your calculations in a notebook. In the quickstart example `geometry` is an object of the `SurfaceGeometry` class. This class has a special method which notebooks hook into to visualize an svg-representation of the object. Try adding a notebook cell with the following content after you have defined your geometry:

```python
geometry
```

This cell should produce the rectangular beam section, and indicate reinforcement bars if you have added those 😃

**Comment by kengwit** [comment]
Hi @mortenengen  Thanks for replying.

1) I am using this version of Python:
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32

List of libraries installed
[installed_libraries.txt](https://github.com/user-attachments/files/17067200/installed_libraries.txt)

2) I was able to visualize the geometry by running it Jupyter notebook. Is there anyway to run it using Python command line? Also

**Comment by mortenengen** [comment]
Thanks for providing this useful information. I was able to recreate your environment, except for the `dotenv` library. Running on 3.10.11, which I have installed my system, I am able to reproduce the exact same `RuntimeWarning` as you reported  👍  However, the warning seems to be only a warning, and the results that we get from `moment_curvature = section.section_calculator.calculate_moment_curvature()` in the example seem to be as intended.

Since I do not get the same warning when running in my dev environment, there seems to be one of the dependencies that causes the issue. I started upgrading one library at a time from the versions you reported. The warning disappears as I upgrade `shapely`, and specifically when I upgrade from 2.0.1 to 2.0.2. I am not able to see exactly what causes this change in behaviour, though.

However, thanks for reporting this, I will update our dependencies to avoid this from now 👍 

To your second question. Good that you were able to visualize it in your notebook. For the moment, we have not exposed this method in the public API, but we have detected the use for it, and are looking into how to implement it in the most elegant way. I will create a separate issue for this.

Finally, please note that the example you are linking to is really work in progress. Perhaps @DanielGMorenaFhecor could advice on how to get it up and running?

**Comment by kengwit** [comment]
@mortenengen Thank you for your response. By the way, I updated to the latest Python version 3.12 and reinstalled structuralcodes so the warning is now gone. I look forward to using a pure Python approach for visualizing geometry and results from structuralcodes.

**Comment by kengwit** [comment]
@mortenengen Thank you for your response. By the way, I updated to the latest Python version 3.12 and reinstalled structuralcodes so the warning is now gone. I look forward to using a pure Python approach for visualizing geometry and results from structuralcodes.
